slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 3.0       
    resolution: 0.05               
    max_laser_range: 16.0          
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.15   
    minimum_travel_heading: 0.1     
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 11.5
    link_match_minimum_response_fine: 0.15  
    link_scan_maximum_distance: 1.2          
    loop_search_maximum_distance: 3.5        
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 2.5  
    loop_match_minimum_response_coarse: 0.4
    loop_match_minimum_response_fine: 0.5

    # Correlation Parameters
    correlation_search_space_dimension: 0.4
    correlation_search_space_resolution: 0.008  
    correlation_search_space_smear_deviation: 0.08  

    # Loop Closure Correlation Parameters
    loop_search_space_dimension: 7.0
    loop_search_space_resolution: 0.04
    loop_search_space_smear_deviation: 0.025

    # Scan Matcher Parameters
    distance_variance_penalty: 0.4
    angle_variance_penalty: 0.9

    fine_search_angle_offset: 0.003  # ~0.17 độ
    coarse_search_angle_offset: 0.3  # ~17 độ
    coarse_angle_resolution: 0.03    # ~1.7 độ
    minimum_angle_penalty: 0.85
    minimum_distance_penalty: 0.45
    use_response_expansion: true
